[package]
name = "tlc"
version = "0.1.0"
description = "Transient Liquid Crystal Experiment Data Processing"
authors = ["yhj.await@gmail.com"]
license = "MIT"
repository = "https://github/starpact/tlc"
default-run = "tlc"
edition = "2021"
rust-version = "1.58"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.5", features = [] }

[dependencies]
tauri = { version = "1.0.0-rc.5", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.17.0", features = ["full"] }
rayon = "1.5"
toml = "0.5.8"
anyhow = "1.0.56"
tracing = "0.1.32"
tracing-subscriber = "0.3.9"
parking_lot = "0.12.0"
ffmpeg-next = "5.0.3"
thread_local = "1.1.4"
image = "0.24.1"
base64 = "0.13.0"
ndarray = { version = "0.15.4", features = ["rayon", "serde"] }
csv = "1.1.6"
calamine = "0.18.0"
plotters = "0.3.1"
median = "0.3.2"
dwt = "0.5.2"
crossbeam = "0.8.1"
arc-swap = "1.5.0"
libm = "0.2.2"
packed_simd = { version = "0.3.7", package = "packed_simd_2" }
approx = "0.5.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.dev]
debug = false
opt-level = 3
