[package]
name = "tlc"
version = "0.1.0"
description = "Transient Liquid Crystal Experiment Data Processing"
authors = ["yhj.await@gmail.com"]
license = "MIT"
repository = "https://github/starpact/tlc"
default-run = "tlc"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.5", features = [] }

[dependencies]
tauri = { version = "1.0.0-rc.5", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.18", features = ["full"] }
rayon = "1.5"
toml = "0.5"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
ffmpeg-next = "5.0"
thread_local = "1.1"
image = "0.24"
base64 = "0.13"
ndarray = { version = "0.15", features = ["rayon", "serde"] }
csv = "1.1"
calamine = "0.18"
plotters = "0.3"
median = "0.3"
dwt = "0.5"
crossbeam = "0.8"
libm = "0.2"
packed_simd = { version = "0.3.8", package = "packed_simd_2" }
approx = "0.5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.dev]
debug = false
opt-level = 3
