[package]
name = "app"
version = "0.1.0"
description = "customized transient liquid crystal"
authors = ["starpact"]
license = "MIT"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4", features = ["codegen"] }

[dependencies]
tauri = { version = "1.0.0-beta", features = ["api-all"] }
tokio = { version = "1.16.1", features = ["full"] }
rayon = "1.5.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
toml = "0.5.8"
anyhow = "1.0.53"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
parking_lot = "0.12.0"
ffmpeg-next = "4.4.0"
thread_local = "1.1.4"
image = "0.24.0"
base64 = "0.13.0"
ndarray = { version = "0.15.4", features = ["rayon", "serde"] }
csv = "1.1.6"
calamine = "0.18.0"
plotters = "0.3.1"
median = "0.3.2"
dwt = "0.5.2"
crossbeam = "0.8.1"
arc-swap = "1.5.0"
libm = "0.2.2"
packed_simd = { version = "0.3.7", package = "packed_simd_2" }
approx = "0.5.1"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]

[profile.dev]
debug = false
opt-level = 3
