[package]
name = "tlc"
version = "0.1.0"
description = "Transient Liquid Crystal Experiment Data Processing"
authors = ["yhj.await@gmail.com"]
license = "MIT"
repository = "https://github/starpact/tlc"
default-run = "tlc"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.1", features = [] }

[dependencies]
tauri = { version = "1.1", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.21", features = ["full"] }
rayon = "1.5"
toml = "0.5"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
thread_local = "1.1"
image = "0.24"
ndarray = { version = "0.15", features = ["rayon", "serde", "approx-0_5"] }
csv = "1.1"
calamine = "0.18"
base64 = "0.13"
plotters = "0.3"
libm = "0.2"
packed_simd = { version = "0.3.8", package = "packed_simd_2" }
once_cell = "1.15.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
thiserror = "1.0.37"
crossbeam = "0.8.2"
function_name = "0.3.0"
tlc-video = { path = "../tlc-video" }
tlc-util = { path = "../tlc-util" }

[dev-dependencies]
mockall = "0.11.2"
approx = "0.5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
