[package]
name = "app"
version = "0.1.0"
description = "customized transient liquid crystal"
authors = ["starpact"]
license = "MIT"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
tokio = { version = "1", features = ["full"] }
rayon = "1.5.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.5.8"
anyhow = "1.0.45"
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
parking_lot = "0.11.2"
ffmpeg-next = "4.4.0"
thread_local = "1.1.3"
image = "0.23.14"
base64 = "0.13.0"
ndarray = { version = "0.15.3", features = ["rayon", "serde"] }
csv = "1.1.6"
calamine = "0.18.0"
plotters = "0.3.1"
median = "0.3.2"
dwt = "0.5.2"
crossbeam = "0.8.1"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]

[profile.dev]
debug = false
opt-level = 3
