[package]
name = "app"
version = "0.1.0"
description = ""
authors = ["you"]
license = "MIT"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.5"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
parking_lot = "0.11"
ffmpeg-next = "4.4.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
