[package]
name = "src-tauri"
version = "0.1.0"
description = "Transient Liquid Crystal Experiment Data Processing"
authors = ["yhj.await@gmail.com"]
license = "MIT"
repository = "https://github/starpact/tlc"
default-run = "src-tauri"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.1", features = [] }

[dependencies]
tauri = { version = "1.2", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.23", features = ["macros"] }
rayon = "1.6"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
thread_local = "1.1"
image = "0.24"
ndarray = { version = "0.15", features = ["rayon", "serde", "approx-0_5"] }
csv = "1.1"
calamine = "0.18"
base64 = "0.13"
plotters = "0.3"
libm = "0.2"
packed_simd = { version = "0.3.8", package = "packed_simd_2" }
once_cell = "1.16"
rusqlite = { version = "0.28.0", features = ["bundled"] }
crossbeam = "0.8"
function_name = "0.3"
tlc-video = { path = "../tlc-video" }
tlc-util = { path = "../tlc-util" }
time = { version = "0.3", features = ["serde", "local-offset", "formatting"] }

[dev-dependencies]
approx = "0.5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
