save_root_dir = "/home/yhj/Documents/2021yhj/EXP/result/imp"
start_frame = 0
start_row = 0
area = [100, 100, 800, 1000]

[video_metadata]
path = "/home/yhj/Documents/2021yhj/EXP/imp/videos/imp_20000_1_up.avi"
frame_rate = 25
nframes = 2444

[daq_metadata]
path = "/home/yhj/Documents/2021yhj/EXP/imp/daq/imp_20000_1.lvm"
nrows = 3000

[physical_param]
peak_temperature = 35.48
solid_thermal_conductivity = 0.19
solid_thermal_diffusivity = 1.091e-7
characteristic_length = 0.015
air_thermal_conductivity = 0.0276
