[path_manager]
video_path = "/Users/yanhongjie/Documents/2021tlc/EXP/imp/video/imp_20000_1_down.avi"
daq_path = "/Users/yanhongjie/Documents/2021tlc/EXP/imp/daq/imp_20000_1.xlsx"
save_root_dir = "/Users/yanhongjie/Documents/2021tlc/EXP/result/imp"

# [timing_parameter]
# frame_rate = 0   # frame rate of video as well as sampling rate of DAQ
# total_frames = 0 # total frames of video
# total_rows = 0   # total raws of DAQ data
# start_frame = 0  # start frame of video involved in the calculation
# start_row = 0    # start row of DAQ data involved in the calculation
# frame_num = 0    # the actual frame number involved in the calculation

# [geometric_parameter]
# video_shape = [500, 500]
# top_left_pos = [0, 0]
# region_shape = [0, 0]

[physical_parameter]
peak_temp = 35.48
solid_thermal_conductivity = 0.19
solid_thermal_diffusivity = 1.091e-7
characteristic_length = 0.015
air_thermal_conductivity = 0.0276
