save_root_dir = "D:\\Archive\\2021yhj\\EXP\\result\\imp"
start_frame = 0
start_row = 0
cal_num = 2333

[video_meta]
path = "D:\\Archive\\2021yhj\\EXP\\imp\\video\\imp_20000_1_up.avi"
frame_rate = 25
total_frames = 2444

[daq_meta]
path = "D:\\Archive\\2021yhj\\EXP\\imp\\daq\\imp_20000_1.lvm"
total_rows = 3000

[physical_param]
peak_temperature = 35.48
solid_thermal_conductivity = 0.19
solid_thermal_diffusivity = 1.091e-7
characteristic_length = 0.015
air_thermal_conductivity = 0.0276
