[package]
name = "tlc-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.23", features = ["macros"] }
rayon = "1.6"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
thread_local = "1.1"
image = "0.24"
ndarray = { version = "0.15", features = ["rayon", "serde", "approx-0_5"] }
csv = "1.1"
calamine = "0.18"
base64 = "0.13"
plotters = "0.3"
libm = "0.2"
packed_simd = { version = "0.3.8", package = "packed_simd_2" }
once_cell = "1.16"
rusqlite = { version = "0.28.0", features = ["bundled"] }
crossbeam = "0.8"
function_name = "0.3"
time = { version = "0.3", features = ["serde", "local-offset", "formatting"] }
salsa = { git = "https://github.com/salsa-rs/salsa", package = "salsa-2022" }
tlc-video = { path = "../tlc-video" }
tlc-util = { path = "../tlc-util" }

[dev-dependencies]
approx = "0.5"
