[package]
name = "tlc-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.27", features = ["sync"] }
rayon = "1.7"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["local-time"] }
thread_local = "1.1"
image = "0.24"
ndarray = { version = "0.15", features = ["rayon", "serde"] }
csv = "1.2"
calamine = "0.19"
base64 = "0.21"
plotters = "0.3"
libm = "0.2"
packed_simd = { version = "0.3.8", package = "packed_simd_2" }
crossbeam = "0.8"
ffmpeg = { version = "5.1", package = "ffmpeg-next" }
median = "0.3"
dwt = "0.5"
time = { version = "0.3", features = ["serde", "local-offset", "formatting"] }
salsa = { git = "https://github.com/salsa-rs/salsa", package = "salsa-2022" }

[dev-dependencies]
approx = "0.5"
ndarray = { version = "0.15", features = ["approx-0_5"] }
tokio = { version = "1.27", features = ["macros", "time"] }
