[package]
name = "tlc"
version = "0.1.0"
authors = ["Starpact <sjtu_yhj@outlook.com>"]
edition = "2018"


[dependencies]
ffmpeg-next = "4.3.7"
ndarray = { version = "0.13.1", features = ["rayon"] }
rayon = "1.3.1"
calamine = "0.16.1"
libc = "0.2.80"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
median = "0.3.1"
plotters = "0.3.0"
lazy_static = "1.4.0"
rbf-interp = "0.1.3"
nalgebra = "0.18.1"
