[package]
name = "tlc"
version = "0.1.0"
authors = ["Starpact <sjtu_yhj@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "4.3.7"
ndarray = {version = "0.13.1", features = ["rayon"]}
rayon = "1.3.1"
calamine = "0.16.1"