[workspace]
members = ["tlc-core", "tlc-server"]

[workspace.dependencies]
ndarray = { version = "0.15", features = ["rayon", "serde"] }

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
