[package]
name = "tlc"
version = "0.1.0"
authors = ["Starpact <sjtu_yhj@outlook.com>"]
edition = "2018"


[dependencies]
ffmpeg-next = "4.3.8"
ndarray = { version = "0.14.0", features = ["rayon"] }
rayon = "1.5.0"
calamine = "0.16.2"
csv = "1.1.5"
libm = "0.2.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
median = "0.3.1"
plotters = "0.3.0"
thread_local = "1.0.2"
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
thiserror = "1.0"
