name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Build
        run: nix develop --command cargo build
      - name: Lint
        run: nix develop --command cargo clippy
      - name: Test
        run: nix develop --command cargo test --verbose
